### ISSUE TITLE
ant build fails at build-jar-jscompress target

### ISSUE THREAD

**Issue by jochem-i** [share-extras/media-viewers#31]
Hi,
the ant build (ant -f project.xml dist-jar) breaks at the ant target "build-jar-jscompress", output:

build-jar-jscompress:

BUILD FAILED
/work/alfresco-add-ons/media-viewers-master/project.xml:9: java.lang.NullPointerException
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSymbolTree(JavaScriptCompressor.java:1190)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.compress(JavaScriptCompressor.java:553)
        at net.noha.tools.ant.yuicompressor.tasks.YuiCompressorTask.compressFile(YuiCompressorTask.java:147)
        at net.noha.tools.ant.yuicompressor.tasks.YuiCompressorTask.execute(YuiCompressorTask.java:100)
...

If you kick out the dependency on it in the build.xml the build works.

Great add-on!
Thanks to the makers!

**Comment by wabson** [comment]
I was not able to reproduce this issue. What version of Ant are you using, and do you have any third party libraries installed into Ant?

**Comment by jochem-i** [comment]
Hi Will,
I used ant version 1.8.4. You are right: I will try a newer ant version and also look for the libraries it uses. That's a good hint cause I also had a similar problem with a complete alfresco compilation about three weeks ago (not exactly the same, but again a js compression thing). 
Sorry, I am still a bit new to the joys of Java project compilations, rather used to the Linux configure-make pains. So I close this issue now. 

Regards
Jochem
